stages:
  - test
  - build

test:
  stage: test
  script:
    - echo "Running tests"
    - npm install
    - npm test

build:
  stage: build
  script:
    - echo "Building the project"
    - npm run build
