import { controlCircuitElements } from './controlCircuit.elements';

type ControlCircuitElement = (typeof controlCircuitElements)[keyof typeof controlCircuitElements];

type ControlCircuitElementsByName = {
	provodOtSilovojChastiSkhemyKAvtomatuPitaniyaUpravleniya: ControlCircuitElement;
	avtomatPitaniyaSkhemyUpravleniya: ControlCircuitElement;
	provodOtAvtomataDoSoyedinitelnojKorobki: ControlCircuitElement;
	provodVSoyedinitelnojKorobkeNaVetkuOtkrytiya: ControlCircuitElement;
	provodOtSoyedinitelnojKorobkiDoKontsevogoVyklyuchatelyaOtkryto: ControlCircuitElement;
	kontsevojVyklyuchatelOtkryto: ControlCircuitElement;
	provodOtKontsevogoVyklyuchatelyaOtkrytoDoKlemmikaKRUZA_P: ControlCircuitElement;
	provodOtKRUZA_PDoVstavkiNDIOtkryto: ControlCircuitElement;
	vstavkaNDIOtkryto: ControlCircuitElement;
	provodOtVstavkiNDIOtkrytoDoNejtrali: ControlCircuitElement;
	provodOtKRUZA_PDoVstavkiNDOOtkryt: ControlCircuitElement;
	vstavkaNDOOtkryt: ControlCircuitElement;
	provodOtVstavkiNDOOtkrytDoKlemmikaKRUZA_P: ControlCircuitElement;
	provodOtKlemmikaKRUZA_PDoKontaktovBlokirovkiSkhemyOtkrytiyaPuskatelyaZakryto: ControlCircuitElement;
	kontaktyBlokirovkiPuskatelyaZakryto: ControlCircuitElement;
	provodOtKontaktovBlokirovkiPuskatelyaZakrytoNaKatushechkuPuskatelyaOtkryto: ControlCircuitElement;
	katushechkaPuskatelyaOtkryt: ControlCircuitElement;
	provodOtKlemmikaKRUZA_PDoKnopkiOtkryt: ControlCircuitElement;
	knopkaOtkryt: ControlCircuitElement;
	provodOtKnopkiOtkrytDoKlemmikaKRUZA_P: ControlCircuitElement;
	provodOtKlemmikaKRUZA_PDoLampyZakryto: ControlCircuitElement;
	lampaZakryto: ControlCircuitElement;
	provodOtLampyZakrytoDoNejtrali: ControlCircuitElement;
	provodVSoyedinitelnojKorobkeNaVetkuZakrytiya: ControlCircuitElement;
	provodOtSoyedinitelnojKorobkiDoKontsevogoVyklyuchatelyaZakryto: ControlCircuitElement;
	kontsevojVyklyuchatelZakryto: ControlCircuitElement;
	provodOtKontsevogoVyklyuchatelyaZakrytoDoKlemmikaKRUZA_P: ControlCircuitElement;
	provodOtKRUZA_PDoVstavkiNDIZakryto: ControlCircuitElement;
	vstavkaNDIZakryto: ControlCircuitElement;
	provodOtVstavkiNDIZakrytoDoNejtrali: ControlCircuitElement;
	provodOtKRUZA_PDoVstavkiNDOZakryt: ControlCircuitElement;
	vstavkaNDOZakryt: ControlCircuitElement;
	provodOtVstavkiNDOZakrytDoKlemmikaKRUZA_P: ControlCircuitElement;
	provodOtKlemmikaKRUZA_PDoKontaktovBlokirovkiSkhemyZakrytiyaPuskatelyaOtkryto: ControlCircuitElement;
	kontaktyBlokirovkiPuskatelyaOtkryto: ControlCircuitElement;
	provodOtKontaktovBlokirovkiPuskatelyaOtkrytoNaKatushechkuPuskatelyaZakryto: ControlCircuitElement;
	katushechkaPuskatelyaZakryt: ControlCircuitElement;
	provodOtKlemmikaKRUZA_PDoKnopkiZakryt: ControlCircuitElement;
	knopkaZakryt: ControlCircuitElement;
	provodOtKnopkiZakrytDoKlemmikaKRUZA_P: ControlCircuitElement;
	provodOtKlemmikaKRUZA_PDoLampyOtkryto: ControlCircuitElement;
	lampaOtkryto: ControlCircuitElement;
	provodOtLampyOtkrytoDoNejtrali: ControlCircuitElement;
};

/**
 * Декларируем человекочитаемые ключи для схемы; ID остаются деталью реализации внутри controlCircuitElements.
 */
export const controlCircuitElementsMap = {
	provodOtSilovojChastiSkhemyKAvtomatuPitaniyaUpravleniya: controlCircuitElements.C0,
	avtomatPitaniyaSkhemyUpravleniya: controlCircuitElements.C1,
	provodOtAvtomataDoSoyedinitelnojKorobki: controlCircuitElements.C2,
	provodVSoyedinitelnojKorobkeNaVetkuOtkrytiya: controlCircuitElements.C3_0_0,
	provodOtSoyedinitelnojKorobkiDoKontsevogoVyklyuchatelyaOtkryto: controlCircuitElements.C3_0_1,
	kontsevojVyklyuchatelOtkryto: controlCircuitElements.C3_0_2,
	provodOtKontsevogoVyklyuchatelyaOtkrytoDoKlemmikaKRUZA_P: controlCircuitElements.C3_0_3,
	provodOtKRUZA_PDoVstavkiNDIOtkryto: controlCircuitElements.C3_0_4_0_0,
	vstavkaNDIOtkryto: controlCircuitElements.C3_0_4_0_1,
	provodOtVstavkiNDIOtkrytoDoNejtrali: controlCircuitElements.C3_0_4_0_2,
	provodOtKRUZA_PDoVstavkiNDOOtkryt: controlCircuitElements.C3_0_4_1_0_0_0,
	vstavkaNDOOtkryt: controlCircuitElements.C3_0_4_1_0_0_1,
	provodOtVstavkiNDOOtkrytDoKlemmikaKRUZA_P: controlCircuitElements.C3_0_4_1_0_0_2,
	provodOtKlemmikaKRUZA_PDoKontaktovBlokirovkiSkhemyOtkrytiyaPuskatelyaZakryto: controlCircuitElements.C3_0_0_1_0,
	kontaktyBlokirovkiPuskatelyaZakryto: controlCircuitElements.C3_0_0_1_1,
	provodOtKontaktovBlokirovkiPuskatelyaZakrytoNaKatushechkuPuskatelyaOtkryto: controlCircuitElements.C3_0_0_1_2,
	katushechkaPuskatelyaOtkryt: controlCircuitElements.C3_0_0_1_4,
	provodOtKlemmikaKRUZA_PDoKnopkiOtkryt: controlCircuitElements.C3_0_4_1_0_1_0,
	knopkaOtkryt: controlCircuitElements.C3_0_4_1_0_1_1,
	provodOtKnopkiOtkrytDoKlemmikaKRUZA_P: controlCircuitElements.C3_0_4_1_0_1_2,
	provodOtKlemmikaKRUZA_PDoLampyZakryto: controlCircuitElements.C3_0_4_2_0,
	lampaZakryto: controlCircuitElements.C3_0_4_2_1,
	provodOtLampyZakrytoDoNejtrali: controlCircuitElements.C3_0_4_2_2,
	provodVSoyedinitelnojKorobkeNaVetkuZakrytiya: controlCircuitElements.C3_1_0,
	provodOtSoyedinitelnojKorobkiDoKontsevogoVyklyuchatelyaZakryto: controlCircuitElements.C3_1_1,
	kontsevojVyklyuchatelZakryto: controlCircuitElements.C3_1_2,
	provodOtKontsevogoVyklyuchatelyaZakrytoDoKlemmikaKRUZA_P: controlCircuitElements.C3_1_3,
	provodOtKRUZA_PDoVstavkiNDIZakryto: controlCircuitElements.C3_1_4_0_0,
	vstavkaNDIZakryto: controlCircuitElements.C3_1_4_0_1,
	provodOtVstavkiNDIZakrytoDoNejtrali: controlCircuitElements.C3_1_4_0_2,
	provodOtKRUZA_PDoVstavkiNDOZakryt: controlCircuitElements.C3_1_4_1_0_0_0,
	vstavkaNDOZakryt: controlCircuitElements.C3_1_4_1_0_0_1,
	provodOtVstavkiNDOZakrytDoKlemmikaKRUZA_P: controlCircuitElements.C3_1_4_1_0_0_2,
	provodOtKlemmikaKRUZA_PDoKontaktovBlokirovkiSkhemyZakrytiyaPuskatelyaOtkryto: controlCircuitElements.C3_1_0_1_0,
	kontaktyBlokirovkiPuskatelyaOtkryto: controlCircuitElements.C3_1_0_1_1,
	provodOtKontaktovBlokirovkiPuskatelyaOtkrytoNaKatushechkuPuskatelyaZakryto: controlCircuitElements.C3_1_0_1_2,
	katushechkaPuskatelyaZakryt: controlCircuitElements.C3_1_0_1_4,
	provodOtKlemmikaKRUZA_PDoKnopkiZakryt: controlCircuitElements.C3_1_4_1_0_1_0,
	knopkaZakryt: controlCircuitElements.C3_1_4_1_0_1_1,
	provodOtKnopkiZakrytDoKlemmikaKRUZA_P: controlCircuitElements.C3_1_4_1_0_1_2,
	provodOtKlemmikaKRUZA_PDoLampyOtkryto: controlCircuitElements.C3_1_4_2_0,
	lampaOtkryto: controlCircuitElements.C3_1_4_2_1,
	provodOtLampyOtkrytoDoNejtrali: controlCircuitElements.C3_1_4_2_2,
} as const satisfies ControlCircuitElementsByName;

export type ControlElementKey = keyof typeof controlCircuitElementsMap;

const exampleOk = controlCircuitElementsMap.knopkaOtkryt;
void exampleOk;

if (false) {
	// @ts-expect-error Проверяем, что нельзя обращаться по внутренним ID.
	void controlCircuitElements.C3_0_4_1_0_1_1;
	// @ts-expect-error Проверяем подсказки по ключам.
	void controlCircuitElementsMap.kNopka;
}
