worker_processes auto;
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name localhost;

        # Указываем директорию со статическими файлами
        root /usr/share/nginx/html;
        index index.html;

        # Обработка маршрутов приложения Next.js (перенаправление на index.html)
        location / {
            try_files $uri /index.html;
        }

        # Логирование запросов
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        # Настройка кеширования статических файлов
        location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|eot|ttf|otf)$ {
            expires 6M;
            access_log off;
            add_header Cache-Control "public";
        }

        # Обработка ошибок
        error_page 404 /index.html;
    }
}