export const WINDOWS = {
	// TA
	// left_top
	w1: {
		currentValue: 1.63,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w2: {
		currentValue: 544,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C',
	},
	w3: {
		currentValue: 238.6,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч',
	},
	w4: {
		currentValue: 13.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w5: {
		currentValue: 539,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C',
	},
	w6: {
		currentValue: 540,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C',
	},
	w7: {
		currentValue: 1.87,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w8: {
		currentValue: 311,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C',
	},
	w9: {
		currentValue: 7.4,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w10: {
		currentValue: 0.38,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мм',
	},
	w11: {
		currentValue: 2999,
		minValue: 0,
		maxValue: 10000,
		unitsMeasurement: 'об/мин',
	},
	w12: {
		currentValue: 1.86,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w13: {
		currentValue: 303,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	// left_mid
	w14: {
		currentValue: 239.7,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч',
	},
	w15: {
		currentValue: 13.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w16: {
		currentValue: 544,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C',
	},
	w17: {
		currentValue: 544,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C',
	},
	w18: {
		currentValue: 1.63,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w19: {
		currentValue: 541,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C',
	},
	w20: {
		currentValue: 489.0,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч',
	},
	w21: {
		currentValue: 18.3,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w22: {
		currentValue: 0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%',
	},
	w23: {
		currentValue: 235,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C',
	},
	w24: {
		currentValue: 1.05,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w25: {
		currentValue: 242,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C',
	},
	w26: {
		currentValue: 0.35,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	// left_down
	w27: {
		currentValue: 407,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм',
	},
	w28: {
		currentValue: 2.86,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w29: {
		currentValue: 407,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм',
	},
	w30: {
		currentValue: 407,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм',
	},
	w31: {
		currentValue: 1.8,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w32: {
		currentValue: 407,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм',
	},
	w33: {
		currentValue: 0.78,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w34: {
		currentValue: 18.8,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w35: {
		currentValue: 152,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C',
	},
	w36: {
		currentValue: 0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А',
	},
	w37: {
		currentValue: 0.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	// mid_top
	w38: {
		currentValue: 0.112,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w39: {
		currentValue: 173,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C',
	},
	w40: {
		currentValue: 448.0,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч',
	},

	// mid_mid
	w41: {
		currentValue: 81,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w42: {
		currentValue: 0.13,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w43: {
		currentValue: 0.08,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w44: {
		currentValue: 50,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w45: {
		currentValue: 2.23,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w46: {
		currentValue: 40,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мм',
	},
	w47: {
		currentValue: 93,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w48: {
		currentValue: 574,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм',
	},
	w49: {
		currentValue: 2.26,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w50: {
		currentValue: 6048.0,
		minValue: 0,
		maxValue: 10000,
		unitsMeasurement: 'т/ч',
	},
	w51: {
		currentValue: 6047.0,
		minValue: 0,
		maxValue: 10000,
		unitsMeasurement: 'т/ч',
	},
	w52: {
		currentValue: 188.9,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'Гкал/ч',
	},
	w53: {
		currentValue: 85,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w54: {
		currentValue: 0.11,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w55: {
		currentValue: 0.12,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w56: {
		currentValue: 0.1,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w57: {
		currentValue: 121,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w58: {
		currentValue: 2413,
		minValue: 0,
		maxValue: 10000,
		unitsMeasurement: 'мм',
	},
	w59: {
		currentValue: 523,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм',
	},
	w60: {
		currentValue: 532,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм',
	},
	w61: {
		currentValue: 472.0,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч',
	},

	// mid_down
	w62: {
		currentValue: 0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А',
	},
	w63: {
		currentValue: 429.0,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'А',
	},
	w64: {
		currentValue: 0.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w65: {
		currentValue: 14.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'кПа',
	},
	w66: {
		currentValue: 2756,
		minValue: 0,
		maxValue: 10000,
		unitsMeasurement: 'об/мин',
	},
	w67: {
		currentValue: 69,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%',
	},

	// right_top
	w68: {
		currentValue: 62,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w69: {
		currentValue: 33,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w70: {
		currentValue: 121,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МВт',
	},
	w71: {
		currentValue: 88.6,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А',
	},
	w72: {
		currentValue: 34,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w73: {
		currentValue: 34,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w74: {
		currentValue: -94.8,
		minValue: -100,
		maxValue: 100,
		unitsMeasurement: 'кПа',
	},

	//right_mid
	w75: {
		currentValue: 9,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w76: {
		currentValue: 0.21,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w77: {
		currentValue: 9,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w78: {
		currentValue: 0.21,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w79: {
		currentValue: 415,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мм',
	},
	w80: {
		currentValue: 11,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w81: {
		currentValue: 0.18,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w82: {
		currentValue: 14,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w83: {
		currentValue: 0.18,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w84: {
		currentValue: 34,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w85: {
		currentValue: 29,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%',
	},
	w86: {
		currentValue: 1.55,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w87: {
		currentValue: 216.1,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч',
	},

	// right_down
	w88: {
		currentValue: 407,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм',
	},
	w89: {
		currentValue: 407,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм',
	},
	w90: {
		currentValue: 0.13,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w91: {
		currentValue: 5.29,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа',
	},
	w92: {
		currentValue: 42,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
	w93: {
		currentValue: 41,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C',
	},
};
