import { Prefix, UnitsMeasurement } from '../types/window';

export const WINDOWS = {
	// TA
	// left_top
	w1: {
		currentValue: 1.63,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w2: {
		currentValue: 544,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w3: {
		currentValue: 238.6,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч' as UnitsMeasurement,
	},
	w4: {
		currentValue: 13.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w5: {
		currentValue: 539,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w6: {
		currentValue: 540,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w7: {
		currentValue: 1.87,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w8: {
		currentValue: 311,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w9: {
		currentValue: 7.4,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w10: {
		currentValue: 0.38,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мм' as UnitsMeasurement,
	},
	w11: {
		currentValue: 2999,
		minValue: 0,
		maxValue: 10000,
		unitsMeasurement: 'об/мин' as UnitsMeasurement,
	},
	w12: {
		currentValue: 1.86,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w13: {
		currentValue: 303,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	// left_mid
	w14: {
		currentValue: 239.7,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч' as UnitsMeasurement,
	},
	w15: {
		currentValue: 13.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w16: {
		currentValue: 544,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w17: {
		currentValue: 544,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w18: {
		currentValue: 1.63,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w19: {
		currentValue: 541,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w20: {
		currentValue: 489.0,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч' as UnitsMeasurement,
	},
	w21: {
		currentValue: 18.3,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w22: {
		currentValue: 0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w23: {
		currentValue: 235,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w24: {
		currentValue: 1.05,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w25: {
		currentValue: 242,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w26: {
		currentValue: 0.35,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	// left_down
	w27: {
		currentValue: 407,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм' as UnitsMeasurement,
		title: 'ПВД-7',
	},
	w28: {
		currentValue: 2.86,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w29: {
		currentValue: 407,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм' as UnitsMeasurement,
	},
	w30: {
		currentValue: 407,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм' as UnitsMeasurement,
		title: 'ПВД-7',
	},
	w31: {
		currentValue: 1.8,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w32: {
		currentValue: 407,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм' as UnitsMeasurement,
		title: 'ПВД-7',
	},
	w33: {
		currentValue: 0.78,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w34: {
		currentValue: 18.8,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w35: {
		currentValue: 152,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w36: {
		currentValue: 0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А' as UnitsMeasurement,
	},
	w37: {
		currentValue: 0.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	// mid_top
	w38: {
		currentValue: 0.112,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w39: {
		currentValue: 173,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w40: {
		currentValue: 448.0,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч' as UnitsMeasurement,
	},
	w94: {
		currentValue: 0.141,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w95: {
		currentValue: 385,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},

	// mid_mid
	w41: {
		currentValue: 81,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w42: {
		currentValue: 0.13,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w43: {
		currentValue: 0.08,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w44: {
		currentValue: 50,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w45: {
		currentValue: 2.23,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w46: {
		currentValue: 40,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мм' as UnitsMeasurement,
		title: 'ПСГ-2',
	},
	w47: {
		currentValue: 93,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w48: {
		currentValue: 574,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм' as UnitsMeasurement,
		title: 'ПСГ-1',
	},
	w49: {
		currentValue: 2.26,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w50: {
		currentValue: 6048.0,
		minValue: 0,
		maxValue: 10000,
		unitsMeasurement: 'т/ч' as UnitsMeasurement,
	},
	w51: {
		currentValue: 6047.0,
		minValue: 0,
		maxValue: 10000,
		unitsMeasurement: 'т/ч' as UnitsMeasurement,
	},
	w52: {
		currentValue: 188.9,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'Гкал/ч' as UnitsMeasurement,
	},
	w53: {
		currentValue: 85,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w54: {
		currentValue: 0.11,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w55: {
		currentValue: 0.12,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w56: {
		currentValue: 0.1,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w57: {
		currentValue: 121,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w58: {
		currentValue: 2413,
		minValue: 0,
		maxValue: 10000,
		unitsMeasurement: 'мм' as UnitsMeasurement,
		title: 'ПВД-3',
	},
	w59: {
		currentValue: 523,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм' as UnitsMeasurement,
		title: 'ПВД-2',
	},
	w60: {
		currentValue: 532,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм' as UnitsMeasurement,
		title: 'ПВД-1',
	},
	w61: {
		currentValue: 472.0,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч' as UnitsMeasurement,
	},

	// mid_down
	w62: {
		currentValue: 0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А' as UnitsMeasurement,
	},
	w63: {
		currentValue: 429.0,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'А' as UnitsMeasurement,
	},
	w64: {
		currentValue: 0.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w65: {
		currentValue: 14.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},
	w66: {
		currentValue: 2756,
		minValue: 0,
		maxValue: 10000,
		unitsMeasurement: 'об/мин' as UnitsMeasurement,
	},
	w67: {
		currentValue: 69,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},

	// right_top
	w68: {
		currentValue: 62,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w69: {
		currentValue: 33,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w70: {
		currentValue: 121,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МВт' as UnitsMeasurement,
	},
	w71: {
		currentValue: 88.6,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А' as UnitsMeasurement,
	},
	w72: {
		currentValue: 34,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w73: {
		currentValue: 34,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w74: {
		currentValue: -94.8,
		minValue: -100,
		maxValue: 100,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},

	//right_mid
	w75: {
		currentValue: 9,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w76: {
		currentValue: 0.21,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w77: {
		currentValue: 9,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w78: {
		currentValue: 0.21,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w79: {
		currentValue: 415,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мм' as UnitsMeasurement,
	},
	w80: {
		currentValue: 11,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w81: {
		currentValue: 0.18,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w82: {
		currentValue: 14,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w83: {
		currentValue: 0.18,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w84: {
		currentValue: 34,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w85: {
		currentValue: 29,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w86: {
		currentValue: 1.55,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w87: {
		currentValue: 216.1,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч' as UnitsMeasurement,
	},

	// right_down
	w88: {
		currentValue: 407,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм' as UnitsMeasurement,
		title: 'Маслобак смазки',
	},
	w89: {
		currentValue: 407,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм' as UnitsMeasurement,
		title: 'Маслобак регулир.',
	},
	w90: {
		currentValue: 0.13,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w91: {
		currentValue: 5.29,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w92: {
		currentValue: 42,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w93: {
		currentValue: 41,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},

	// KA
	// left_top
	w96: {
		currentValue: 0,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'об/мин' as UnitsMeasurement,
	},

	w97: {
		currentValue: 802,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'об/мин' as UnitsMeasurement,
	},
	w98: {
		currentValue: 903,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'об/мин' as UnitsMeasurement,
	},
	w99: {
		currentValue: 860,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'об/мин' as UnitsMeasurement,
	},
	w100: {
		currentValue: 683,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'об/мин' as UnitsMeasurement,
	},
	w101: {
		currentValue: 0,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'об/мин' as UnitsMeasurement,
	},
	w102: {
		currentValue: 0.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'A' as UnitsMeasurement,
	},
	w103: {
		currentValue: 16.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'A' as UnitsMeasurement,
	},
	w104: {
		currentValue: 13.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'A' as UnitsMeasurement,
	},
	w105: {
		currentValue: 10.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'A' as UnitsMeasurement,
	},
	w106: {
		currentValue: 16.1,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'A' as UnitsMeasurement,
	},
	w107: {
		currentValue: 0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'A' as UnitsMeasurement,
	},
	w108: {
		currentValue: 18,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мм' as UnitsMeasurement,
	},
	w109: {
		currentValue: 14,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мм' as UnitsMeasurement,
	},
	w110: {
		currentValue: 21,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мм' as UnitsMeasurement,
	},
	w111: {
		currentValue: 3248,
		minValue: 0,
		maxValue: 10000,
		unitsMeasurement: 'об/мин' as UnitsMeasurement,
	},
	w112: {
		currentValue1: 407,
		currentValue2: 407,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'мм' as UnitsMeasurement,
	},

	// left_mid
	w113: {
		currentValue: null,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w114: {
		currentValue: null,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w115: {
		currentValue: 397,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w116: {
		currentValue: null,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w117: {
		currentValue: null,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w118: {
		currentValue: 39,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w119: {
		currentValue: 0.07,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'кВт' as UnitsMeasurement,
	},
	w120: {
		currentValue: 364.4,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'кВт' as UnitsMeasurement,
	},
	w121: {
		currentValue: 389.3,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'кВт' as UnitsMeasurement,
	},
	w122: {
		currentValue: 362.9,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'кВт' as UnitsMeasurement,
	},
	w123: {
		currentValue: 397.7,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'кВт' as UnitsMeasurement,
	},
	w124: {
		currentValue: 0.0,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'кВт' as UnitsMeasurement,
	},
	w125: {
		currentValue: 0.07,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},
	w126: {
		currentValue: 0.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},
	w127: {
		currentValue: 0.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},
	w128: {
		currentValue: 0.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},
	w129: {
		currentValue: 0.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},
	w130: {
		currentValue: 0.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},
	w131: {
		currentValue: 74,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w132: {
		currentValue: 162,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w133: {
		currentValue: 178,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w134: {
		currentValue: 175,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w135: {
		currentValue: 179,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w136: {
		currentValue: 47,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},

	// left_down
	w137: {
		currentValue: 2.8,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w138: {
		currentValue: 4587.0,
		minValue: 0,
		maxValue: 10000,
		unitsMeasurement: 'кг/ч' as UnitsMeasurement,
	},
	w139: {
		currentValue: 2.8,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},

	//mid_top
	w140: {
		currentValue: 302,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
		prefix: 'А' as Prefix,
	},
	w141: {
		currentValue: 307,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
		prefix: 'Б' as Prefix,
	},
	w142: {
		currentValue: 414,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w143: {
		currentValue: 411,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w144: {
		currentValue: 397,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w145: {
		currentValue: 399,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w146: {
		currentValue: null,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w147: {
		currentValue: 9,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w148: {
		currentValue: 474,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w149: {
		currentValue: 482,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w150: {
		currentValue: 225,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w151: {
		currentValue: 326,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w152: {
		currentValue: 460,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w153: {
		currentValue: 463,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w154: {
		currentValue: 542,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w155: {
		currentValue: 542,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w156: {
		currentValue: 525,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w157: {
		currentValue: 528,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w158: {
		currentValue: 0.144,
		minValue: 0,
		maxValue: 1,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
		prefix: 'dP' as Prefix,
	},
	w159: {
		currentValue: 0.146,
		minValue: 0,
		maxValue: 1,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
		prefix: 'dP' as Prefix,
	},
	w160: {
		currentValue: 520,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w161: {
		currentValue: 525,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},

	// mid_mid
	w162: {
		currentValue: -0.2,
		minValue: -1,
		maxValue: 0,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},
	w163: {
		currentValue: 499,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'м3/ч' as UnitsMeasurement,
	},
	w164: {
		currentValue: -0.045,
		minValue: -1,
		maxValue: 0,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},
	w165: {
		currentValue: 332,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w166: {
		currentValue: -0.045,
		minValue: -1,
		maxValue: 0,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},
	w167: {
		currentValue: 1.05,
		minValue: 0,
		maxValue: 10,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},
	w168: {
		currentValue: 333,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w169: {
		currentValue: 552,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w170: {
		currentValue: 5.4,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w171: {
		currentValue: 6.4,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w172: {
		currentValue: 6.4,
		minValue: 0,
		maxValue: 10,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w173: {
		currentValue: 131,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w174: {
		currentValue: 584,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w175: {
		currentValue: 15.8,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w176: {
		currentValue: 6.3,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w177: {
		currentValue: 144,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w178: {
		currentValue: 133,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},

	//mid_down
	w179: {
		currentValue: 4633.0,
		minValue: 0,
		maxValue: 10000,
		unitsMeasurement: 'кг/ч' as UnitsMeasurement,
	},
	w180: {
		currentValue: 96,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},

	//right_top
	w181: {
		currentValue: 542,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w182: {
		currentValue: 539,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w183: {
		currentValue: 542,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w184: {
		currentValue: 13.1,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w185: {
		currentValue: 244,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч' as UnitsMeasurement,
	},
	w186: {
		currentValue: 72,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мм' as UnitsMeasurement,
	},
	w187: {
		currentValue: 72,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мм' as UnitsMeasurement,
	},
	w188: {
		currentValue: 0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w189: {
		currentValue: 539,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w200: {
		currentValue: 13.1,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w201: {
		currentValue: 242,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч' as UnitsMeasurement,
	},
	w202: {
		currentValue: 5,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч' as UnitsMeasurement,
	},
	w203: {
		currentValue: 496,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч' as UnitsMeasurement,
	},

	//right_mid
	w204: {
		currentValue: 66,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w205: {
		currentValue: 64,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w206: {
		currentValue: 0.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А' as UnitsMeasurement,
	},
	w207: {
		currentValue: 70.3,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А' as UnitsMeasurement,
	},
	w208: {
		currentValue: 422,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'м3/ч^1000' as UnitsMeasurement,
	},
	w209: {
		currentValue: 0.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А' as UnitsMeasurement,
	},
	w210: {
		currentValue: 68.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А' as UnitsMeasurement,
	},
	w211: {
		currentValue: 0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w212: {
		currentValue: 42,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w213: {
		currentValue: 54,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w214: {
		currentValue: 54,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w215: {
		currentValue: 491,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: 'т/ч' as UnitsMeasurement,
	},
	w216: {
		currentValue: 18.2,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'МПа' as UnitsMeasurement,
	},
	w217: {
		currentValue: 236,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w218: {
		currentValue: 48,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},
	w219: {
		currentValue: 49,
		minValue: 0,
		maxValue: 1000,
		unitsMeasurement: '°C' as UnitsMeasurement,
	},

	// right_down
	w220: {
		currentValue: 53,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w221: {
		currentValue: 45,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w222: {
		currentValue: 89.2,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А' as UnitsMeasurement,
	},
	w223: {
		currentValue: 59.2,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А' as UnitsMeasurement,
	},
	w224: {
		currentValue: 54.3,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А' as UnitsMeasurement,
	},
	w225: {
		currentValue: 55,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w226: {
		currentValue: 41,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w227: {
		currentValue: 88.6,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'А' as UnitsMeasurement,
	},
	w228: {
		currentValue: null,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w229: {
		currentValue: null,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: '%' as UnitsMeasurement,
	},
	w230: {
		currentValue: null,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мг/м3' as UnitsMeasurement,
	},
	w231: {
		currentValue: null,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мг/м3' as UnitsMeasurement,
	},
	w232: {
		currentValue: null,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мг/м3' as UnitsMeasurement,
	},
	w233: {
		currentValue: null,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'мг/м3' as UnitsMeasurement,
	},
	w234: {
		currentValue: 4.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},
	w235: {
		currentValue: 4.0,
		minValue: 0,
		maxValue: 100,
		unitsMeasurement: 'кПа' as UnitsMeasurement,
	},
};
